name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4

      - name: Get tag
        id: tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc libgl1-mesa-dev xorg-dev

      - name: Build binaries
        run: |
          mkdir -p dist
          # Windows
          GOOS=windows GOARCH=amd64 go build -o dist/yt-dlp-simpgo-windows-amd64.exe -ldflags "-X 'main.Version=${{ steps.tag.outputs.tag }}' -s -w -H=windowsgui"
          # Linux
          GOOS=linux GOARCH=amd64 go build -o dist/yt-dlp-simpgo-linux-amd64 -ldflags "-X 'main.Version=${{ steps.tag.outputs.tag }}' -s -w"
          # macOS Intel
          GOOS=darwin GOARCH=amd64 go build -o dist/yt-dlp-simpgo-darwin-amd64 -ldflags "-X 'main.Version=${{ steps.tag.outputs.tag }}' -s -w"
          # macOS Apple Silicon
          GOOS=darwin GOARCH=arm64 go build -o dist/yt-dlp-simpgo-darwin-arm64 -ldflags "-X 'main.Version=${{ steps.tag.outputs.tag }}' -s -w"

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
